[package]
name = "dreamcore"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["shared/abi", "userland/api", "userland/runtime"]
resolver = "2"

[dependencies]
limine = "0.5.0"
imagineos-abi = { path = "shared/abi" }

[[bin]]
name = "dreamcore"
path = "kernel/src/main.rs"
test = false

[[bin]]
name = "bootstrap"
path = "bootstrap/bootstrap.rs"
test = false
bench = false

[features]
kernel-debug = []
bootstrap = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1