#ifndef IMAGINEOS_COMMON_SYSCALL_NUMBERS_H
#define IMAGINEOS_COMMON_SYSCALL_NUMBERS_H

#define SYS_READ  0
#define SYS_WRITE 1
#define SYS_EXIT  60

#define STDIN_FILENO  0
#define STDOUT_FILENO 1
#define STDERR_FILENO 2

#define EBADF  9
#define EFAULT 14
#define ENOSYS 38

#endif